### ISSUE TITLE
AttributeError: 'module' object has no attribute 'GraphAPI'

### ISSUE THREAD

**Issue by mansigoel** [iamgroot42/FB_Spammer#1]
When installed modules from scratch, we get this error

**Comment by iamgroot42** [comment]
Strange. It works for other users. Try this? :

```
sudo pip uninstall facebook
sudo pip uninstall facebook-sdk
sudo pip install facebook-sdk
```

**Comment by mansigoel** [comment]
Tried. No luck

**Comment by iamgroot42** [comment]
Removing all external dependencies. https://github.com/iamgroot42/fb_spammer/commit/f04e23973575cf31c02c08cbba64996c57370e18 takes care of the errors you just mentioned.
