### ISSUE TITLE
Facebook temporarily blocks account

### ISSUE THREAD

**Issue by abhishek-nigam** [iamgroot42/FB_Spammer#5]
I tried using your handy tool to publicise about event in my college, but after about 10 posts. Facebook temporarily blocked my account saying that they detected suspicious activity. Yes, I was able to unblock my account by resetting my password.

Is there any way this problem can be solved? Also, on using it seems like as someone is actually typing all the posts by hand, can the facebook API be used instead for this that it's faster and it doesn't get blocked??

**Comment by iamgroot42** [comment]
Hey @abhishek-nigam 
To avoid being blocked by Facebook, you can tweak the waiting period after every post in the code. If this problem could be solved, you would be swarmed with spam every second :)
Facebook, like any other tech giant, uses sophisticated spam/automation detection tools. The Graph API can be used for this purpose but has limited capabilities. The very purpose of making it look like it's being typed by hand is to avoid automation detection.
