### ISSUE TITLE
AttributeError: module 'facebook' has no attribute 'GraphAPI'

### ISSUE THREAD

**Issue by poornima198m** [iamgroot42/FB_Spammer#6]
my code is
import os
import json
import facebook
 
if __name__=='__main__':
    token = os.environ.get('FACEBOOK_TEMP_TOKEN')
    graph = facebook.GraphAPI(token)
    profile = graph.get_object('me',fields = 'name,location{}')
    print (json.dumps(profile,indent=4))

**Comment by iamgroot42** [comment]
The same code snippet worked for me. Make sure you've installed `facebook-sdk` via `pip`, and that there's no other pip package for Facebook; I've seen a few Facebook-based packages clash with each other.

**Comment by rosscg** [comment]
Also, make sure you're script is not named facebook.py or it will clash with the module name.
